// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRp53SikARypWlx_us2-_VRQcCEJ6A6Y',
    appId: '1:555230414391:web:40530cbd4c38ac2b1f21b2',
    messagingSenderId: '555230414391',
    projectId: 'first-16338',
    authDomain: 'first-16338.firebaseapp.com',
    storageBucket: 'first-16338.appspot.com',
    measurementId: 'G-44YC7X37DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAquBCHkMMY9o732bFQUo8s6QzW2YpBkF0',
    appId: '1:555230414391:android:0dcdce4eb1a59f411f21b2',
    messagingSenderId: '555230414391',
    projectId: 'first-16338',
    storageBucket: 'first-16338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD28o5qCz7ecpRkdGpXRkh1_z2nNLbMU8g',
    appId: '1:555230414391:ios:08a0f19b8e1fc69b1f21b2',
    messagingSenderId: '555230414391',
    projectId: 'first-16338',
    storageBucket: 'first-16338.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD28o5qCz7ecpRkdGpXRkh1_z2nNLbMU8g',
    appId: '1:555230414391:ios:08a0f19b8e1fc69b1f21b2',
    messagingSenderId: '555230414391',
    projectId: 'first-16338',
    storageBucket: 'first-16338.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRp53SikARypWlx_us2-_VRQcCEJ6A6Y',
    appId: '1:555230414391:web:adbd7769cb7d1ac91f21b2',
    messagingSenderId: '555230414391',
    projectId: 'first-16338',
    authDomain: 'first-16338.firebaseapp.com',
    storageBucket: 'first-16338.appspot.com',
    measurementId: 'G-8QE6WCFVPT',
  );
}
